//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheque.Test.Project.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TestWebServiceSoap")]
    public interface TestWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChequeDetails", ReplyAction="*")]
        Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse ChequeDetails(Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChequeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse> ChequeDetailsAsync(Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChequeDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChequeDetails", Namespace="http://tempuri.org/", Order=0)]
        public Cheque.Test.Project.ServiceReference1.ChequeDetailsRequestBody Body;
        
        public ChequeDetailsRequest() {
        }
        
        public ChequeDetailsRequest(Cheque.Test.Project.ServiceReference1.ChequeDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Number;
        
        public ChequeDetailsRequestBody() {
        }
        
        public ChequeDetailsRequestBody(string Name, string Number) {
            this.Name = Name;
            this.Number = Number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChequeDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChequeDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cheque.Test.Project.ServiceReference1.ChequeDetailsResponseBody Body;
        
        public ChequeDetailsResponse() {
        }
        
        public ChequeDetailsResponse(Cheque.Test.Project.ServiceReference1.ChequeDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChequeDetailsResult;
        
        public ChequeDetailsResponseBody() {
        }
        
        public ChequeDetailsResponseBody(string ChequeDetailsResult) {
            this.ChequeDetailsResult = ChequeDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestWebServiceSoapChannel : Cheque.Test.Project.ServiceReference1.TestWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestWebServiceSoapClient : System.ServiceModel.ClientBase<Cheque.Test.Project.ServiceReference1.TestWebServiceSoap>, Cheque.Test.Project.ServiceReference1.TestWebServiceSoap {
        
        public TestWebServiceSoapClient() {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse Cheque.Test.Project.ServiceReference1.TestWebServiceSoap.ChequeDetails(Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest request) {
            return base.Channel.ChequeDetails(request);
        }
        
        public string ChequeDetails(string Name, string Number) {
            Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest inValue = new Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest();
            inValue.Body = new Cheque.Test.Project.ServiceReference1.ChequeDetailsRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Number = Number;
            Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse retVal = ((Cheque.Test.Project.ServiceReference1.TestWebServiceSoap)(this)).ChequeDetails(inValue);
            return retVal.Body.ChequeDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse> Cheque.Test.Project.ServiceReference1.TestWebServiceSoap.ChequeDetailsAsync(Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest request) {
            return base.Channel.ChequeDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cheque.Test.Project.ServiceReference1.ChequeDetailsResponse> ChequeDetailsAsync(string Name, string Number) {
            Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest inValue = new Cheque.Test.Project.ServiceReference1.ChequeDetailsRequest();
            inValue.Body = new Cheque.Test.Project.ServiceReference1.ChequeDetailsRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Number = Number;
            return ((Cheque.Test.Project.ServiceReference1.TestWebServiceSoap)(this)).ChequeDetailsAsync(inValue);
        }
    }
}
