//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChequeWritingApp.ChequeWritingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChequeWritingService.ChequeWritingWebServiceSoap")]
    public interface ChequeWritingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name InputNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChequeService", ReplyAction="*")]
        ChequeWritingApp.ChequeWritingService.ChequeServiceResponse ChequeService(ChequeWritingApp.ChequeWritingService.ChequeServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChequeService", ReplyAction="*")]
        System.Threading.Tasks.Task<ChequeWritingApp.ChequeWritingService.ChequeServiceResponse> ChequeServiceAsync(ChequeWritingApp.ChequeWritingService.ChequeServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChequeServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChequeService", Namespace="http://tempuri.org/", Order=0)]
        public ChequeWritingApp.ChequeWritingService.ChequeServiceRequestBody Body;
        
        public ChequeServiceRequest() {
        }
        
        public ChequeServiceRequest(ChequeWritingApp.ChequeWritingService.ChequeServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InputNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        public ChequeServiceRequestBody() {
        }
        
        public ChequeServiceRequestBody(string InputNumber, string Name) {
            this.InputNumber = InputNumber;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChequeServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChequeServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ChequeWritingApp.ChequeWritingService.ChequeServiceResponseBody Body;
        
        public ChequeServiceResponse() {
        }
        
        public ChequeServiceResponse(ChequeWritingApp.ChequeWritingService.ChequeServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChequeServiceResult;
        
        public ChequeServiceResponseBody() {
        }
        
        public ChequeServiceResponseBody(string ChequeServiceResult) {
            this.ChequeServiceResult = ChequeServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChequeWritingWebServiceSoapChannel : ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeWritingWebServiceSoapClient : System.ServiceModel.ClientBase<ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap>, ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap {
        
        public ChequeWritingWebServiceSoapClient() {
        }
        
        public ChequeWritingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeWritingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeWritingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeWritingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ChequeWritingApp.ChequeWritingService.ChequeServiceResponse ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap.ChequeService(ChequeWritingApp.ChequeWritingService.ChequeServiceRequest request) {
            return base.Channel.ChequeService(request);
        }
        
        public string ChequeService(string InputNumber, string Name) {
            ChequeWritingApp.ChequeWritingService.ChequeServiceRequest inValue = new ChequeWritingApp.ChequeWritingService.ChequeServiceRequest();
            inValue.Body = new ChequeWritingApp.ChequeWritingService.ChequeServiceRequestBody();
            inValue.Body.InputNumber = InputNumber;
            inValue.Body.Name = Name;
            ChequeWritingApp.ChequeWritingService.ChequeServiceResponse retVal = ((ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap)(this)).ChequeService(inValue);
            return retVal.Body.ChequeServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ChequeWritingApp.ChequeWritingService.ChequeServiceResponse> ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap.ChequeServiceAsync(ChequeWritingApp.ChequeWritingService.ChequeServiceRequest request) {
            return base.Channel.ChequeServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ChequeWritingApp.ChequeWritingService.ChequeServiceResponse> ChequeServiceAsync(string InputNumber, string Name) {
            ChequeWritingApp.ChequeWritingService.ChequeServiceRequest inValue = new ChequeWritingApp.ChequeWritingService.ChequeServiceRequest();
            inValue.Body = new ChequeWritingApp.ChequeWritingService.ChequeServiceRequestBody();
            inValue.Body.InputNumber = InputNumber;
            inValue.Body.Name = Name;
            return ((ChequeWritingApp.ChequeWritingService.ChequeWritingWebServiceSoap)(this)).ChequeServiceAsync(inValue);
        }
    }
}
